steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m cp -r . gs://static-site1234
        gsutil -m acl ch -r -u AllUsers:R gs://static-site1234

# Optional: specify a timeout
timeout: "300s"
options:
    logging: CLOUD_LOGGING_ONLY